var SEGS=[
{t:"Depuis des années, Carrow Lake traînait cette réputation de ville hantée que les réseaux adoraient transformer en légende. Disparitions, silhouettes dans la brume, lumières sur le lac… Tout le pays connaissait les histoires.",bg:0,c:''},
{t:"C'était précisément pour ça qu'il était venu.",bg:0,c:'ni ns'},
{t:"Son premier trail longue distance.\nUne ville isolée.\nDes sentiers traversant la forêt et longeant le lac noir.",bg:0,c:'nl'},
{t:"L'endroit parfait pour décrocher un peu.",bg:0,c:'ni ns'},
{t:"Il jeta son téléphone sur le lit sans même répondre. Trente minutes à peine qu'il était arrivé et quelqu'un avait déjà décidé de jouer au fantôme local. Le timing était presque drôle.",bg:1,c:''},
{t:"Dans le couloir de l'hôtel, le vieux parquet grinçait sous chacun de ses pas. L'endroit sentait le bois humide et la cheminée froide. Une odeur ancienne, comme si les murs avaient absorbé trop d'hivers sans jamais sécher complètement.",bg:1,c:''},
{t:"En descendant les escaliers, il remarqua quelque chose qu'il n'avait pas vu en arrivant : derrière le comptoir vide de la réception, toutes les clés étaient suspendues…",bg:1,c:''},
{t:"Sauf une.\n\nLa numéro 12.\n\nSa chambre.",bg:1,c:'nl nb'},
{t:"Il continua sans y réfléchir davantage.",bg:1,c:'ni ns'},
{t:"Dehors, l'air était plus froid que prévu. Le lac disparaissait presque entièrement dans le brouillard du soir, mais on distinguait encore sa surface immobile entre les maisons. Pas une ride. Pas un bruit d'eau.",bg:2,c:''},
{t:"Même le vent semblait éviter Carrow Lake.",bg:2,c:'ni ns'},
{t:"Le Café du Port était encore ouvert malgré l’heure tardive. Une lumière jaune débordait des fenêtres embuées, et le faible brouhaha des conversations donnait enfin l’impression d’un endroit normal.",bg:3,c:''},
{t:"Elyos entra.",bg:3,c:'ns'},
{t:"La chaleur le frappa immédiatement, accompagnée de l’odeur du café brûlé et de soupe maison. Quelques habitués parlaient à voix basse sans vraiment rire. Tous semblaient fatigués. Pas physiquement. Autrement.",bg:3,c:''},
{t:"Comme des gens qui dormaient mal depuis longtemps.",bg:3,c:'ni ns'},
{t:"Il s’installa près d’une fenêtre et commanda simplement un plat chaud. Le serveur nota sans sourire.",bg:3,c:''},
{t:"Puis, au moment où Elyos posa son téléphone sur la table…",bg:4,c:'ni ns'},
{t:"Quelqu’un l’observait.",bg:4,c:'ns nb'},
{t:"Au fond du restaurant.\nDerrière l’angle d’un mur.",bg:4,c:'nl'},
{t:"Juste une partie du visage apparaissait.",bg:4,c:''},
{t:"Un œil.\nUne joue pâle.\nDes doigts immobiles accrochés au coin du mur.",bg:4,c:'nl'},
{t:"Elyos fronça légèrement les sourcils.",bg:4,c:''},
{t:"Impossible de savoir si c’était un homme ou une femme. Le visage semblait… trop neutre. Comme si quelque chose n’allait pas dans ses proportions sans qu’il puisse dire quoi. Les cheveux humides collaient à la peau blanche. Et surtout, la personne ne détournait jamais le regard.",bg:4,c:''},
{t:"Jamais.",bg:4,c:'ni'},
{t:"Même lorsque le serveur passa devant.\nMême lorsqu’un client se leva.\nMême lorsque Elyos soutint son regard pendant plusieurs secondes.",bg:4,c:'nl'},
{t:"Aucune réaction.",bg:4,c:''},
{t:"Il eut finalement un petit rire discret pour lui-même.",bg:3,c:''},
{t:"Certainement un local un peu étrange essayant de renforcer l’ambiance “ville maudite” pour les touristes.",bg:3,c:''},
{t:"Pourtant…",bg:4,c:'ni ns'},
{t:"Au moment où son plat arriva, il réalisa quelque chose qui lui serra brièvement l’estomac :",bg:4,c:''},
{t:"Personne, dans le restaurant, ne semblait remarquer la silhouette derrière le mur.",bg:4,c:''},
{t:"Pas un regard.\nPas une hésitation.",bg:4,c:'nl'},
{t:"Comme si elle n’existait que pour lui.",bg:4,c:'ni ns'},
{t:"Elyos mangea malgré tout. Lentement. Calmement. Il était du genre rationnel. Terre à terre. Il avait toujours détesté les gens qui transformaient chaque coïncidence en phénomène paranormal.",bg:3,c:''},
{t:"Un message anonyme.\nUn habitant bizarre.\nUne ville étrange.",bg:3,c:'nl'},
{t:"Voilà tout.",bg:3,c:''},
{t:"Quand il quitta le café, la silhouette n’était plus là.",bg:5,c:''},
{t:"Mais en passant devant la vitre extérieure du restaurant, il aperçut son reflet dans le verre noirci par la nuit.",bg:5,c:''},
{t:"Et juste derrière lui…",bg:5,c:'ni ns'},
{t:"Quelqu’un semblait se tenir dans la rue.",bg:5,c:'ns'},
{t:"Immobile.",bg:5,c:'ni'},
{t:"Lorsqu’il se retourna, il n’y avait personne.",bg:6,c:'ns'},
{t:"Seulement le brouillard.",bg:6,c:'ni ns'},
{t:"Il remonta dans sa chambre et partit se coucher.",bg:6,c:'ns'}
];